#!/bin/sh -e

: "${EDITOR=nano}"

if [ "$#" -lt 2 ]; then 
	cat << EOF
Usage: ${0##*/} config [filename]

Downloads a config to autoexec.cfg (or another absolute filename if specified).
EOF
    exit 64
fi


#steamUsername="$1"
config="$1"
outputFile="$2"
configURL="https://raw.githubusercontent.com/fwinest-JediThug/tf2configs/master/$config"

if [ -z "$outputFile" ]; then
    outputDir="$HOME/.local/share/Steam/SteamApps/common/Team Fortress 2/tf/custom/tf2configs/cfg"
    [ -d "$outputDir" ] || outputDir="$HOME/Steam/SteamApps/common/Team Fortress 2/tf/custom/tf2configs/cfg"
    mkdir -p "$outputDir"
    outputFile="$outputDir/$filename"
fi

if [ -e "$outputFile" ]; then
    read -rp "Warning! $outputFile exists, overwrite? (y/N) " outputFileReply
    [ "$outputFileReply" != y ] && exit 1 
fi

wget -qO "$outputFile" -- "$configURL"

read -rp "Open config file in $EDITOR? (y/N) " editorReply
[ "$editorReply" = y ] && "$EDITOR" "$outputFile"

cat << EOF
Config "$config" loaded into $outputFile.
Add the following to your TF2 launch options (Library -> TF2 -> Properties -> Launch Options):"
NOTE: Replace WIDTH and HEIGHT as appropriate.

EOF
awk '$2=="-dxlevel" { sub(/-dxlevel [[:digit:]]+/, "") ; sub(/^\/\/ /, "") ; print } ' < "$outputFile"
